### ISSUE TITLE
How to create a client for this application

### ISSUE THREAD

**Issue by ashwin-raj** [fedyunin/qbwcpoc#4]
How to create a client for this application

**Comment by fedyunin** [comment]
Could you provide more details? Do you need client for qbwcpoc?

**Comment by ashwin-raj** [comment]
I have an application. If I click Vendor save button from my application then the vendor details need to pass to the QB. Is that possible ? How?

**Comment by fedyunin** [comment]
Sure this is possible, but this will be work by next way:
1. Your application should provide webservice for interact with QB via QB WebConnector. (Example of this webservice is QBWCPoC)
2. You create Vendor in your app. Vendor will be saved in the your application database with flag: not synchronized with QB.
3. When QB Webconnector initiate update (by user or by scheduler) - QB Webconnector call webservice method from your app. Your webservice collect all data from database with flag not synchronized. And then saves them in the QB.

So looks like this is not possible. Because only QB WebConnector can initiate interaction from your app/webservice. So your app need to save somewhere created object until next call from QB WebConnector.

Hope this help you. Let me know if something not clear.

**Comment by ashwin-raj** [comment]
Thanks Dude. I understood well. Let me try and back

**Comment by ashwin-raj** [comment]
I try to create a client stub using the wsdl file and access the server through stub. But it is not connect to QB web connector. Do you know why?

**Comment by fedyunin** [comment]
Which wsdl file you used for create stub?

**Comment by ashwin-raj** [comment]
In this Application within the web content there is a wsdl file is there. The same one only

**Comment by fedyunin** [comment]
Sorry for late response. 

In this case you can't connect to QB web connector. Only QB web connector connects to your service.

QB web connector is client for your web service - that provided by your app.

**Comment by ashwin-raj** [comment]
Thanks.
